// Optimized variants are generated by scripts/optimize-images.mjs at build time.
export const PHOTO_WIDTHS = [480, 960, 1600] as const;

const BASE = process.env.NEXT_PUBLIC_BASE_PATH || "";

export function photoSrc(file: string, width: (typeof PHOTO_WIDTHS)[number] = 960) {
  return `${BASE}/_img/${file}-${width}.webp`;
}

export function photoSrcSet(file: string) {
  return PHOTO_WIDTHS.map((w) => `${photoSrc(file, w)} ${w}w`).join(", ");
}
